package com.example.wishlistapp.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

// Entity annotation specifies that this class represents a table in the Room database
@Entity(tableName = "wish-table")
data class Wish(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L, // Primary key, auto-generated by the database

    @ColumnInfo(name = "wish-title")
    val title: String = "", // Title of the wish

    @ColumnInfo(name = "wish-desc")
    val description: String = "" // Description of the wish
)
